name: NSW Registration Data
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  archive:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: master
    - uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn
    - name: Run script
      run: node run.js
      timeout-minutes: 5
    - name: Push to data branch
      run: |
        cd data
        git config user.name jxeeno
        git config user.email ken+github@jxeeno.com
        git add . || exit 0
        git commit -m "auto(): update feeds" || exit 0
        git push || exit 0